@protocol = http 
@hostname = localhost 
@port = {{$dotenv PORT}} 
@host = {{protocol}}://{{hostname}}:{{port}} 
@contentType = application/json 

### GET all products
GET {{host}}/products HTTP/1.1 
content-type: {{contentType}}

### Create Order 
POST {{host}}/orders HTTP/1.1 
content-type: {{contentType}} 

{
    "<product_name>": [
        { "sugar": "<number>", "ice": "<number>" },
        ...
    ],
    ...
}
